[project]
name = "whatcmd"
version = "0.0.1"
description = 'A CLI that displays a categorized list of useful linux commands with short explanations'
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
whatcmd = "whatcmd.cli:whatcmd"

[tool.black]
line-length = 79
